### ISSUE TITLE
John Hopkins conform

### ISSUE THREAD

**Issue by cmarxmeier** [KeyvanSadri/covid-19-RKI#1]
file names in  KeyvanSadri/covid-19-RKI and CSSEGISandData /COVID-19  differ.

had to change node-red scripting from 
https://flows-new.nodered.org/flow/3bfc75934d243f528867852c55bb64a1
to match in flow:
  return year + '-' + month + '-' + day;
  
[covid19_flow_node-red.json.txt](https://github.com/KeyvanSadri/covid-19-RKI/files/4338504/covid19_flow_node-red.json.txt)

now imports properly to map:

https://node-red.netsecdb.de/node-red/covid19/

**Comment by KeyvanSadri** [comment]
Hi,

thanks for your comment. I will fix the filename.
