### ISSUE TITLE
csv Header Death(s)

### ISSUE THREAD

**Issue by cmarxmeier** [KeyvanSadri/covid-19-RKI#2]
John Hopkins csv shows 'Deaths' instead of 'Death'
changed flow to parse Dataset:

[covid19_deaths.json.txt](https://github.com/KeyvanSadri/covid-19-RKI/files/4340224/covid19_deaths.json.txt)
![Firefox_Screenshot_2020-03-16T20-23-31 430Z](https://user-images.githubusercontent.com/1956798/76796888-b1ab3c00-67cc-11ea-8b89-653f15154b22.png)

**Comment by KeyvanSadri** [comment]
Fixed!

**Comment by cmarxmeier** [comment]
now works properly with original flow and repo url changed to KeyvanSadri/covid-19-RKI/:

https://node-red.netsecdb.de/node-red/covid19/

tnx

**Comment by cmarxmeier** [comment]
fixed.
